/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Diagnostics {
  'samaveda48Exists' : boolean,
  'mantraCount' : bigint,
  'metadataCount' : bigint,
  'samaveda47Exists' : boolean,
}
export type ExternalBlob = Uint8Array;
export type Language = { 'hindi' : null } |
  { 'telugu' : null } |
  { 'english' : null };
export type Veda = { 'atharvaVeda' : null } |
  { 'samaVeda' : null } |
  { 'yajurVeda' : null } |
  { 'rikVeda' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMantraAudioFile' : ActorMethod<[Veda, bigint, ExternalBlob], undefined>,
  'getAllMantraNumbersForVeda' : ActorMethod<[Veda], Array<bigint>>,
  'getBackendDiagnostics' : ActorMethod<[], Diagnostics>,
  'getMantraAudioFile' : ActorMethod<[Veda, bigint], [] | [ExternalBlob]>,
  'getMantraMeaning' : ActorMethod<[Veda, bigint, Language], [] | [string]>,
  'getMantraMetadata' : ActorMethod<[Veda, bigint, Language], [] | [string]>,
  'getMantraNumbers' : ActorMethod<[Veda], Array<bigint>>,
  'getMantraTemplate' : ActorMethod<[Veda, bigint], [] | [string]>,
  'getMantraText' : ActorMethod<[Veda, bigint, Language], [] | [string]>,
  'submitTemplate' : ActorMethod<[Veda, bigint, string], Array<bigint>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];