/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Veda = IDL.Variant({
  'atharvaVeda' : IDL.Null,
  'samaVeda' : IDL.Null,
  'yajurVeda' : IDL.Null,
  'rikVeda' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'telugu' : IDL.Null,
  'english' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMantraAudioFile' : IDL.Func([Veda, IDL.Nat, ExternalBlob], [], []),
  'getAllMantraNumbersForVeda' : IDL.Func(
      [Veda],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getMantraAudioFile' : IDL.Func(
      [Veda, IDL.Nat],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getMantraMeaning' : IDL.Func(
      [Veda, IDL.Nat, Language],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getMantraMetadata' : IDL.Func(
      [Veda, IDL.Nat, Language],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getMantraNumbers' : IDL.Func([Veda], [IDL.Vec(IDL.Nat)], ['query']),
  'getMantraTemplate' : IDL.Func(
      [Veda, IDL.Nat],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getMantraText' : IDL.Func(
      [Veda, IDL.Nat, Language],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'submitTemplate' : IDL.Func(
      [Veda, IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Veda = IDL.Variant({
    'atharvaVeda' : IDL.Null,
    'samaVeda' : IDL.Null,
    'yajurVeda' : IDL.Null,
    'rikVeda' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'telugu' : IDL.Null,
    'english' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMantraAudioFile' : IDL.Func([Veda, IDL.Nat, ExternalBlob], [], []),
    'getAllMantraNumbersForVeda' : IDL.Func(
        [Veda],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getMantraAudioFile' : IDL.Func(
        [Veda, IDL.Nat],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getMantraMeaning' : IDL.Func(
        [Veda, IDL.Nat, Language],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMantraMetadata' : IDL.Func(
        [Veda, IDL.Nat, Language],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMantraNumbers' : IDL.Func([Veda], [IDL.Vec(IDL.Nat)], ['query']),
    'getMantraTemplate' : IDL.Func(
        [Veda, IDL.Nat],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMantraText' : IDL.Func(
        [Veda, IDL.Nat, Language],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'submitTemplate' : IDL.Func(
        [Veda, IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };