/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Veda = IDL.Variant({
  'atharvaVeda' : IDL.Null,
  'samaVeda' : IDL.Null,
  'yajurVeda' : IDL.Null,
  'rikVeda' : IDL.Null,
});
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'telugu' : IDL.Null,
  'english' : IDL.Null,
});

export const idlService = IDL.Service({
  'getMantraMeaning' : IDL.Func(
      [Veda, IDL.Nat, Language],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getMantraNumbers' : IDL.Func([Veda], [IDL.Vec(IDL.Nat)], ['query']),
  'getMantraText' : IDL.Func(
      [Veda, IDL.Nat, Language],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Veda = IDL.Variant({
    'atharvaVeda' : IDL.Null,
    'samaVeda' : IDL.Null,
    'yajurVeda' : IDL.Null,
    'rikVeda' : IDL.Null,
  });
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'telugu' : IDL.Null,
    'english' : IDL.Null,
  });
  
  return IDL.Service({
    'getMantraMeaning' : IDL.Func(
        [Veda, IDL.Nat, Language],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMantraNumbers' : IDL.Func([Veda], [IDL.Vec(IDL.Nat)], ['query']),
    'getMantraText' : IDL.Func(
        [Veda, IDL.Nat, Language],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };